# Generated by Django 5.2.13 on 2026-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='dgda_license',
            field=models.CharField(blank=True, help_text='DGDA regulatory license number', max_length=100),
        ),
    ]
