# Generated by Django 5.0.1 on 2026-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_shop_dgda_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
