# Generated by Django 5.2.13 on 2026-04-13 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinventory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='adjusted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.shopinventory'),
        ),
        migrations.AddIndex(
            model_name='shopinventory',
            index=models.Index(fields=['shop'], name='shop_invent_shop_id_564665_idx'),
        ),
        migrations.AddIndex(
            model_name='shopinventory',
            index=models.Index(fields=['master_medicine'], name='shop_invent_master__bd53c4_idx'),
        ),
        migrations.AddIndex(
            model_name='shopinventory',
            index=models.Index(fields=['expiry_date'], name='shop_invent_expiry__559747_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopinventory',
            unique_together={('shop', 'master_medicine', 'batch_number')},
        ),
    ]
