# Generated by Django 5.0.1 on 2026-04-15 09:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCustomMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('generic', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('powder', 'Powder'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('suggested_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Custom Medicine',
                'verbose_name_plural': 'Shop Custom Medicines',
                'db_table': 'shop_custom_medicines',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop'], name='shop_custom_shop_id_27e78d_idx'), models.Index(fields=['brand_name'], name='shop_custom_brand_n_7bff84_idx')],
                'unique_together': {('shop', 'brand_name', 'strength')},
            },
        ),
    ]
