# Generated by Django 5.0.1 on 2026-04-15 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shopcustommedicine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.shopinventory'),
        ),
        migrations.CreateModel(
            name='ShopCustomMedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(max_length=100)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_inventories', to='inventory.shopcustommedicine')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Custom Medicine Inventory',
                'verbose_name_plural': 'Shop Custom Medicine Inventories',
                'db_table': 'shop_custom_medicine_inventory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='custom_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.shopcustommedicineinventory'),
        ),
        migrations.AddIndex(
            model_name='shopcustommedicineinventory',
            index=models.Index(fields=['shop'], name='shop_custom_shop_id_8fe160_idx'),
        ),
        migrations.AddIndex(
            model_name='shopcustommedicineinventory',
            index=models.Index(fields=['custom_medicine'], name='shop_custom_custom__1e7ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='shopcustommedicineinventory',
            index=models.Index(fields=['expiry_date'], name='shop_custom_expiry__82516e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopcustommedicineinventory',
            unique_together={('shop', 'custom_medicine', 'batch_number')},
        ),
    ]
