# Generated by Django 5.2.13 on 2026-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField(unique=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('allopathic', 'Allopathic'), ('herbal', 'Herbal'), ('homeopathic', 'Homeopathic')], max_length=20)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('powder', 'Powder'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], max_length=50)),
                ('generic', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=200)),
                ('package_container', models.TextField()),
                ('package_size', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Catalog',
                'verbose_name_plural': 'Master Catalog',
                'db_table': 'master_catalog',
                'ordering': ['brand_name'],
                'indexes': [models.Index(fields=['brand_name'], name='master_cata_brand_n_7668b2_idx'), models.Index(fields=['generic'], name='master_cata_generic_3b00a7_idx'), models.Index(fields=['manufacturer'], name='master_cata_manufac_dcf129_idx'), models.Index(fields=['slug'], name='master_cata_slug_74a6ef_idx')],
            },
        ),
    ]
