# Generated by Django 5.0.1 on 2026-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercatalog',
            name='suggested_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Suggested master price for reference', max_digits=10),
        ),
    ]
